name: Ejecución de acciones de TestBoost

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio TestBoost
      uses: actions/checkout@v3
      with:
        repository: javalenciacai/test.james.api.suma
        ref: dev

    - name: Ejecutar script de instalación de dependencias
      run: |
        sudo timedatectl set-timezone America/Bogota
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Ejecutar script de sumar
      continue-on-error: true
      run: pytest src/test_suites/api --html=src/report/reportAPI.html --self-contained-html

    # Publish HTML report
    - uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: HTML-report
        path: src/report/

                
      # Publish HTML report as page          
    - name: "Publish src results"
      if: ${{ always() }}
      uses: peaceiris/actions-gh-pages@v3.7.3
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: './src/report'
        keep_files: true
