name: Mi acción personalizada

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3
    
    - name: Acción personalizada en otro repositorio
      uses: javalenciacai/TestBoost@master
      with:
       action: actions/build-linux
