name: Ejecución de acciones de TestBoost

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio TestBoost
      uses: actions/checkout@v3
      with:
        repository: javalenciacai/TestBoost
        ref: master

    - name: Ejecutar script de instalación de dependencias
      run: |
        sudo timedatectl set-timezone America/Bogota
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Ejecutar script de unittest
      run: python -m unittest discover \src
