name: Mi acción personalizada

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Acción personalizada en otro repositorio
      uses: javalenciacai/playwright.test.python@master
