name: Mi acción personalizada

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Acción personalizada en otro repositorio
      uses: javalenciacai/playwright.test.python@master
